resolver: nightly-2020-12-14

packages:
  - .

extra-deps:
- git: https://github.com/martijnbastiaan/haskell-hedgehog.git
  commit: 41e87d110d3b2b7b522d29d7c0500672f2640dcc
  subdirs:
    - hedgehog
- git: https://github.com/cchalmers/circuit-notation.git
  commit: 0fe897cb95bd1be87abed044f4072f104dec2f7d

flags:
  clash-prelude:
    # 'large-tuples' generates tuple instances for various classes up to the
    # GHC imposed maximum of 62 elements. This severely slows down compiling
    # Clash, and triggers Template Haskell bugs on Windows. Hence, we disable
    # it by default. This will be the default for Clash >=1.4.
    large-tuples: false

allow-newer: true
