name: CI

# Trigger the workflow on all pull requests and pushes/merges to master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: Stack tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Stack / GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-${{ github.sha }}
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      # Ask Stack to use system GHC instead of installing its own copy
      - name: Use system GHC
        run: |
          stack config set system-ghc --global true

      - name: Test with Stack
        run: |
          .ci/test_stack.sh

  cabal:
    name: Cabal tests - ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal:
          - "3.2"
        ghc:
          - "8.10.7"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-${{ github.sha }}
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ github.ref }}-
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Build
        run: |
          cabal build all -fci

      - name: Test
        run: |
          .ci/test_cabal.sh

      - name: Documentation
        run: |
          .ci/build_docs.sh

  linting:
    name: Source code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Whitespace
        run: |
          .ci/test_whitespace.sh
